ColmanAppStore/Models/AppVideo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ColmanAppStore.Models
{
    public class AppVideo
    { 
        public int Id { get; set; }

        [Required]
        [Display(Name = "Video name")]
        public string Name { get; set; }

        [Required]
        public string Video { get; set; }

        [Display(Name = "App name")]
        public int AppId { get; set; }

        public App App { get; set; } //ONE app to ONE video
    }
}

ColmanAppStore/Controllers/AppVideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ColmanAppStore.Data;
using ColmanAppStore.Models;
using Microsoft.AspNetCore.Authorization;

namespace ColmanAppStore.Controllers
{
    public class AppVideosController : Controller
    {
        private readonly ColmanAppStoreContext _context;

        public AppVideosController(ColmanAppStoreContext context)
        {
            _context = context;
        }

        // GET: AppVideos
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Index()
        {
            String userName = User.Identity.Name;
            foreach (var item in _context.User)
            {
                if (item.Name.Equals(userName))
                {
                    if (User.IsInRole("Admin")) //admin user
                    {
                        return View(await _context.AppVideo.Include(a => a.App).ToListAsync());
                    }
                    else //programer user
                    {
                        var colmanAppStoreContext = _context.AppVideo.Include(a => a.App).Where(x => x.App.DeveloperName.Equals(item.Name));
                        return View(await colmanAppStoreContext.ToListAsync());
                    }
                }
            }
            // in case couldn't find the user (can't happen when logged in)
            return View(await _context.AppVideo.ToListAsync());
        }

        // GET: AppVideos/Details/5
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var appVideo = await _context.AppVideo.Include(a => a.App).FirstOrDefaultAsync(m => m.Id == id);
            if (appVideo == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            String userName = User.Identity.Name;
            Boolean isAdmin = User.IsInRole("Admin");
            if (!appVideo.App.DeveloperName.Equals(userName) && !isAdmin)
                return RedirectToAction("AccessDenied", "Users");

            return View(appVideo);
        }

        // GET: AppVideos/Create
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: AppVideos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Create([Bind("Id,Name,Video")] AppVideo appVideo)
        {
            if (ModelState.IsValid)
            {
                appVideo.AppId = 49; //default app before change in app's create
                _context.Add(appVideo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(appVideo);
        }

        // GET: AppVideos/Edit/5
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            var appVideo = await _context.AppVideo.Include(a => a.App).FirstOrDefaultAsync(m => m.Id == id);
            if (appVideo == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            string userName = User.Identity.Name;
            string appDevName = _context.AppVideo.Find(id).App.DeveloperName;
            Boolean isAdmin = User.IsInRole("Admin");
            if ((userName != appDevName) && !isAdmin)
            {
                return RedirectToAction("AccessDenied", "Users");
            }

            if (User.IsInRole("Admin")) //admin user
            {
                ViewData["AppId"] = new SelectList(_context.Apps.Where(a => a.Id != 49), "Id", "Name", appVideo.AppId);
            }
            else //programer user
            {
                ViewData["AppId"] = new SelectList(_context.Apps.Where(a => a.Id != 49).Where(x => x.DeveloperName.Equals(userName)), "Id", "Name", appVideo.AppId);
            }

            return View(appVideo);
        }

        // POST: AppVideos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Video,AppId")] AppVideo appVideo)
        {
            if (id != appVideo.Id)
            {
                return RedirectToAction("NotFound", "Home");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appVideo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppVideoExists(appVideo.Id))
                    {
                        return RedirectToAction("NotFound", "Home");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            string userName = User.Identity.Name;
            if (User.IsInRole("Admin")) //admin user
            {
                ViewData["AppId"] = new SelectList(_context.Apps.Where(a => a.Id != 49), "Id", "Name", appVideo.AppId);
            }
            else //programer user
            {
                ViewData["AppId"] = new SelectList(_context.Apps.Where(a => a.Id != 49).Where(x => x.DeveloperName.Equals(userName)), "Id", "Name", appVideo.AppId);
            }

            return View(appVideo);
        }

        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> SearchAppVideo(string query) //search by app name
        {
            string userName = User.Identity.Name;
            var searchContext = _context.AppVideo.Include(l => l.App).
                 Where(a => a.App.Name.Contains(query) || (query == null));
            if (!User.IsInRole("Admin")) // if developer - he will see only his apps (admin sees everything)
            {
                searchContext = _context.AppVideo.Include(l => l.App).
                  Where(a => a.App.Name.Contains(query) || (query == null)).Where(u => u.App.DeveloperName.Equals(userName));
            }
            return View("SearchAppVideo", await searchContext.ToListAsync());
        }

        // GET: AppVideos/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            var appVideo = await _context.AppVideo.Include(a => a.App).FirstOrDefaultAsync(m => m.Id == id);
            if (appVideo == null)
            {
                return NotFound();
            }
            string userName = User.Identity.Name;
            string appDevName = _context.AppVideo.Find(id).App.DeveloperName;
            Boolean isAdmin = User.IsInRole("Admin");
            if ((userName != appDevName) && !isAdmin)
            {
                return RedirectToAction("AccessDenied", "Users");
            }
            return View(appVideo);
        }

        // POST: AppVideos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appVideo = await _context.AppVideo.FindAsync(id);
            _context.AppVideo.Remove(appVideo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppVideoExists(int id)
        {
            return _context.AppVideo.Any(e => e.Id == id);
        }
    }
}

ColmanAppStore/Views/AppVideos/Create.cshtml
@model ColmanAppStore.Models.AppVideo

@{
    ViewData["Title"] = "Create";
}

<h1 id="PageHeader">Create app video</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Video" class="control-label"></label>
                <input asp-for="Video" class="form-control" />
                <span asp-validation-for="Video" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ColmanAppStore/Views/AppVideos/Delete.cshtml
@model ColmanAppStore.Models.AppVideo

@{
    ViewData["Title"] = "Delete";
}

<h1 id="PageHeader">@Model.Name delete</h1>

<h4 id="subTitleHeader">Are you sure you want to delete this?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Video)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Video)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.App)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.App.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ColmanAppStore/Views/AppVideos/Details.cshtml
@model ColmanAppStore.Models.AppVideo

@{
    ViewData["Title"] = Model.Name + " details";
}

<h1 id="PageHeader">@Model.Name details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Video)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Video)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.App)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.App.Name)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> 
    <a class="btn btn-outline-info" asp-action="Index">Back to List</a>
</div>

ColmanAppStore/Views/AppVideos/Edit.cshtml
@model ColmanAppStore.Models.AppVideo

@{
    ViewData["Title"] = "Edit";
}

<h1 id="PageHeader">@Model.Name edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Video" class="control-label"></label>
                <input asp-for="Video" class="form-control" />
                <span asp-validation-for="Video" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppId" class="control-label"></label>
                <select asp-for="AppId" class="form-control" asp-items="ViewBag.AppId"></select>
                <span asp-validation-for="AppId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ColmanAppStore/Views/AppVideos/Index.cshtml
@model IEnumerable<ColmanAppStore.Models.AppVideo>

@{
    ViewData["Title"] = "All app Videos";
    <link rel="stylesheet" href="~/css/AppVideoStyle.css" />
}

<div class="row">
    <div class="col-lg-9 col-md-10">
        <h1 id="AppVideoHeader">All App Videos</h1>
    </div>

    <div class="col-lg-3 col-md-2">
        <form id="searchAppVideo" asp-action="SearchAppVideo" asp-controller="AppVideos" class="d-flex">
            <input id="font" name="query" type="search" class="form-control" placeholder="Search by App Name" aria-label="Search" aria-describedby="search-addon" autocomplete="off" />
            <div id="slider-range"></div>
        </form>
    </div>
</div>

<p>
    <a class="btn btn-outline-info" asp-action="Create">Create New Video</a>
</p>

@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Video)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.App)
                </th>
                <th>
                    Edit
                </th>
                <th>
                    Details
                </th>
                <th>
                    Delete
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Video)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.App.Name)
                    </td>
                    <td>
                        <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    </td>
                    <td>
                        <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    </td>
                    <td>
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <br />
    <h2 class="text-center" id="PageHeader">Sorry, you don't have any app videos</h2>
    <br />
}

ColmanAppStore/Views/AppVideos/SearchAppVideo.cshtml
@model IEnumerable<ColmanAppStore.Models.AppVideo>

@{
    ViewData["Title"] = "All app Videos";
    <link rel="stylesheet" href="~/css/AppVideoStyle.css" />
}

<div class="row">
    <div class="col-lg-9 col-md-10">
        <h1 id="AppVideoHeader">Search Results</h1>
    </div>

    <div class="col-lg-3 col-md-2">
        <form id="searchAppVideo" asp-action="SearchAppVideo" asp-controller="AppVideos" class="d-flex">
            <input id="font" name="query" type="search" class="form-control" placeholder="Search by App Name" aria-label="Search" aria-describedby="search-addon" autocomplete="off" />
            <div id="slider-range"></div>
        </form>
    </div>
</div>

<p>
    <a class="btn btn-outline-info" asp-action="Create">Create New Video</a>
</p>

@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Video)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.App)
                </th>
                <th>
                    Edit
                </th>
                <th>
                    Details
                </th>
                <th>
                    Delete
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Video)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.App.Name)
                    </td>
                    <td>
                        <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    </td>
                    <td>
                        <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    </td>
                    <td>
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <br />
    <h2 class="text-center" id="PageHeader">Sorry, you don't have any app videos</h2>
    <br />
}