ColmanAppStore/Models/PaymentMethod.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ColmanAppStore.Models
{
    public class PaymentMethod
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Name on card")]
        [Required(ErrorMessage = "You must enter name")]
        public string NameOnCard { get; set; }
        
        [Display(Name = "Card number")]
        [Required(ErrorMessage = "You must enter credit card number")]
        public long CardNumber { get; set; }

        [Display(Name = "Expired date")]
        [Required(ErrorMessage = "You must enter expired date")]
        public String ExpiredDate { get; set; }

        [Required(ErrorMessage = "You must enter cvv")]
        [Range(100,9999,ErrorMessage = "The password must be at 3 or 4 digits")]
        public int CVV { get; set; }

        [Display(Name = "ID number")]
        [Required(ErrorMessage = "You must enter Id")]
        [Range(100000000, 999999999, ErrorMessage = "The password must be 9 characters")]
        public long IdNumber { get; set; }

        public List<Payment> Payments { get; set; } //ONE payment method to MANY payments

        [Display(Name = "Choose users who can use the card")]
        public List<User> Users { get; set; } //MANY users to MANY payment methods
    }
}

ColmanAppStore/Controllers/PaymentMethodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ColmanAppStore.Data;
using ColmanAppStore.Models;
using Microsoft.AspNetCore.Authorization;

namespace ColmanAppStore.Controllers
{
    public class PaymentMethodsController : Controller
    {
        private readonly ColmanAppStoreContext _context;

        public PaymentMethodsController(ColmanAppStoreContext context)
        {
            _context = context;
        }

        // GET: PaymentMethods
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Index()
        {
            String userName = User.Identity.Name;
            var usr = _context.User.Include(u => u.PaymentMethods).Include(u => u.AppListUser);

            foreach (var item in usr)
            {
                if (item.Name.Equals(userName))
                {
                    var paymentmethods = _context.PaymentMethod.Where(i => i.Users.Contains(item));
                    return View(await paymentmethods.ToListAsync());
                }
            }
            return View(await _context.PaymentMethod.ToListAsync());
        }

        // GET: PaymentMethods/Details/5
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            var paymentMethod = await _context.PaymentMethod.Include(u => u.Users).FirstOrDefaultAsync(m => m.Id == id);
            if (paymentMethod == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            //Checks if the user has access to card details
            List<User> cardUser = paymentMethod.Users;
            string userName = User.Identity.Name;
            int flag = 0;
            foreach (var item in cardUser)
            {
                if (item.Name.Contains(userName))
                {
                    flag++;
                    break;
                }
            }
            if (flag == 0)
                return RedirectToAction("AccessDenied", "Users");

            return View(paymentMethod);
        }

        // GET: PaymentMethods/Create
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Name");
            return View();
        }

        // POST: PaymentMethods/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Create([Bind("Id,NameOnCard,CardNumber,ExpiredDate,CVV,IdNumber")] PaymentMethod paymentMethod, int[] Users)
        {
            if (ModelState.IsValid)
            {
                paymentMethod.Users = new List<User>();
                var usr = _context.User.Include(u => u.PaymentMethods).Include(u => u.AppListUser);

                foreach (var item in usr)
                {
                    if (Users.Contains(item.Id)) //update user list depend on which users can use the payment method
                    {
                        paymentMethod.Users.Add(item);
                    }
                }

                _context.Add(paymentMethod);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("HomePage", "Apps");
        }

        // GET: PaymentMethods/Edit/5
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            var paymentMethod = await _context.PaymentMethod.Include(u => u.Users).FirstOrDefaultAsync(m => m.Id == id);
            if (paymentMethod == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            //Checks if the user has access to card details
            List<User> cardUser = paymentMethod.Users;
            string userName = User.Identity.Name;
            int flag = 0;
            foreach (var item in cardUser)
            {
                if (item.Name.Contains(userName))
                {
                    flag++;
                    break;
                }
            }
            if (flag == 0)
                return RedirectToAction("AccessDenied", "Users");


            return View(paymentMethod);
        }

        // POST: PaymentMethods/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NameOnCard,CardNumber,ExpiredDate,CVV,IdNumber")] PaymentMethod paymentMethod)
        {
            if (id != paymentMethod.Id)
            {
                return RedirectToAction("NotFound", "Home");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paymentMethod);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentMethodExists(paymentMethod.Id))
                    {
                        return RedirectToAction("NotFound", "Home");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(paymentMethod);
        }

        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> SearchPaymentMethod(int query) //search by id
        {
            var searchContext = _context.PaymentMethod.Where(a => a.IdNumber == query);
            return View("searchPaymentMethod", await searchContext.ToListAsync());
        }

        // GET: PaymentMethods/Delete/5
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            var paymentMethod = await _context.PaymentMethod.Include(u => u.Users).FirstOrDefaultAsync(m => m.Id == id);
            if (paymentMethod == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            //Checks if the user has access to card details
            List<User> cardUser = paymentMethod.Users;
            string userName = User.Identity.Name;
            int flag = 0;
            foreach (var item in cardUser)
            {
                if (item.Name.Contains(userName))
                {
                    flag++;
                    break;
                }
            }
            if (flag == 0)
                return RedirectToAction("AccessDenied", "Users");

            return View(paymentMethod);
        }

        // POST: PaymentMethods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paymentMethod = await _context.PaymentMethod.FindAsync(id);
            var pm = _context.PaymentMethod.Include(u => u.Users);

            foreach (var p in pm)
            {
                if (p.Id == id)
                {
                    if (p.Users.Count() == 1) //connected to only one user
                    {
                        _context.PaymentMethod.Remove(paymentMethod);
                    }
                    else
                    {
                        String userName = User.Identity.Name;
                        var usr = _context.User.Include(p => p.PaymentMethods);
                        foreach (var us in usr)
                        {
                            if (us.Name.Equals(userName))
                            {
                                us.PaymentMethods.Remove(p); //remove the current payment method ONLY for the connected user
                                break;
                            }
                        }
                    }
                }
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentMethodExists(int id)
        {
            return _context.PaymentMethod.Any(e => e.Id == id);
        }
    }
}

ColmanAppStore/Views/PaymentMethods/Create.cshtml
@model ColmanAppStore.Models.PaymentMethod

@{
    ViewData["Title"] = "Create";
    <link rel="stylesheet" href="~/css/paymentMethodStyle.css" />
}

<h1 id="PageHeader">Create new payment method</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameOnCard" class="control-label"></label>
                <input asp-for="NameOnCard" class="form-control" />
                <span asp-validation-for="NameOnCard" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardNumber" class="control-label"></label>
                <input asp-for="CardNumber" class="form-control" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpiredDate" class="control-label"></label>
                <input asp-for="ExpiredDate" class="form-control" />
                <span asp-validation-for="ExpiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CVV" class="control-label"></label>
                <input asp-for="CVV" class="form-control" />
                <span asp-validation-for="CVV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNumber" class="control-label"></label>
                <input asp-for="IdNumber" class="form-control" />
                <span asp-validation-for="IdNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Users" class="control-label"></label>
                <select asp-for="Users" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="Users" class="text-danger"></span>
            </div>

            <input type="hidden" name="UserName" value="@User.Identity.Name" />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ColmanAppStore/Views/PaymentMethods/Delete.cshtml
@model ColmanAppStore.Models.PaymentMethod

@{
    ViewData["Title"] = "Delete";
    <link rel="stylesheet" href="~/css/paymentMethodStyle.css" />
}

<h1 id="PageHeader">Delete payment method</h1>

<h4 id="subTitleHeader">Are you sure you want to delete this?</h4>
<div>
    <hr />
    <div class="card_payment col-12" id="cardDetails">
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.NameOnCard)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.NameOnCard)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.CardNumber)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.CardNumber)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.ExpiredDate)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.ExpiredDate)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.CVV)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.CVV)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.IdNumber)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.IdNumber)
                </dd>
            </dl>
            <br />
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a asp-action="Index">Back to List</a>
            </form>
        </div>
    </div>
</div>

ColmanAppStore/Views/PaymentMethods/Details.cshtml
@model ColmanAppStore.Models.PaymentMethod

@{
    ViewData["Title"] = "Details";
    <link rel="stylesheet" href="~/css/paymentMethodStyle.css" />
}

<h1 id="PageHeader">Payment method details</h1>

<div>
    <hr />
    <div class="card_payment col-12" id="cardDetails">
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.NameOnCard)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.NameOnCard)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.CardNumber)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.CardNumber)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.ExpiredDate)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.ExpiredDate)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.CVV)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.CVV)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.IdNumber)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.IdNumber)
                </dd>
            </dl>
            <br />
            <div>
                <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> 
                <a class="btn btn-outline-info" asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</div>

ColmanAppStore/Views/PaymentMethods/Edit.cshtml
@model ColmanAppStore.Models.PaymentMethod

@{
    ViewData["Title"] = "Edit payment method";
    <link rel="stylesheet" href="~/css/paymentMethodStyle.css" />
}

<h1 id="PageHeader">Edit payment method</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NameOnCard" class="control-label"></label>
                <input asp-for="NameOnCard" class="form-control" />
                <span asp-validation-for="NameOnCard" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardNumber" class="control-label"></label>
                <input asp-for="CardNumber" class="form-control" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpiredDate" class="control-label"></label>
                <input asp-for="ExpiredDate" class="form-control" />
                <span asp-validation-for="ExpiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CVV" class="control-label"></label>
                <input asp-for="CVV" class="form-control" />
                <span asp-validation-for="CVV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNumber" class="control-label"></label>
                <input asp-for="IdNumber" class="form-control" />
                <span asp-validation-for="IdNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ColmanAppStore/Views/PaymentMethods/Index.cshtml
@model IEnumerable<ColmanAppStore.Models.PaymentMethod>

@{
    ViewData["Title"] = "All payment methods";
    <link rel="stylesheet" href="~/css/paymentMethodStyle.css" />
}

<div class="row">
    <div class="col-lg-9 col-md-10">
        <h1 id="PaymentMethodHeader">Credit cards</h1>
    </div>

    <div class="col-lg-3 col-md-2">
        <form id="searchPaymentMethod" asp-action="searchPaymentMethod" asp-controller="PaymentMethods" class="d-flex">
            <input id="font" name="query" type="search" class="form-control" placeholder="Search by Id number" aria-label="Search" aria-describedby="search-addon" autocomplete="off" />
            <div id="slider-range"></div>
        </form>
    </div>

</div>

@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NameOnCard)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CardNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExpiredDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CVV)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IdNumber)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NameOnCard)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CardNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpiredDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CVV)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdNumber)
                    </td>
                    <td>
                        <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                        <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Details</a> 
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <br />
    <h2 class="text-center" id="PageHeader">Sorry, you don't have any payment methods</h2>
    <br />
}

ColmanAppStore/Views/PaymentMethods/SearchPaymentMethod.cshtml
@model IEnumerable<ColmanAppStore.Models.PaymentMethod>

@{
    ViewData["Title"] = "All payment methods";
    <link rel="stylesheet" href="~/css/paymentMethodStyle.css" />
}

<div class="row">
    <div class="col-lg-9 col-md-10">
        <h1 id="PaymentMethodHeader">Search results</h1>
    </div>

    <div class="col-lg-3 col-md-2">
        <form id="searchPaymentMethod" asp-action="searchPaymentMethod" asp-controller="PaymentMethods" class="d-flex">
            <input id="font" name="query" type="search" class="form-control" placeholder="Search by Id number" aria-label="Search" aria-describedby="search-addon" autocomplete="off" />
            <div id="slider-range"></div>
        </form>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NameOnCard)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CardNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpiredDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CVV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNumber)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NameOnCard)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CardNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpiredDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CVV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdNumber)
                </td>
                <td>
                    <a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                    <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Details</a> 
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>