ColmanAppStore/Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ColmanAppStore.Data;
using ColmanAppStore.Models;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;

namespace ColmanAppStore.Controllers
{
    public class AppsController : Controller
    {
        private readonly ColmanAppStoreContext _context;

        public AppsController(ColmanAppStoreContext context)
        {
            _context = context;
        }

        // GET: Apps
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin")) //Admin can see all apps (include apps in default category)
            {
                var colmanAppStoreContext = _context.Apps.Include(a => a.Category).Include(l => l.Logo).Where(a => a.Id != 49);
                return View(await colmanAppStoreContext.ToListAsync());
            }
            else
            {
                var colmanAppStoreContext = _context.Apps.Include(a => a.Category).Include(l => l.Logo).Where(a => a.Id != 49).Where(a => a.CategoryId != 9);
                return View(await colmanAppStoreContext.ToListAsync());
            }
        }

        //Search by name and category 
        public async Task<IActionResult> Search(string query)
        {
            var searchContext = _context.Apps.Include(l => l.Logo).Include(c => c.Category).Where(a => a.Id != 49).
                Where(a => a.Name.Contains(query) || a.Category.Name.Contains(query) || a.DeveloperName.Equals(query) || (query == null));
            return View("Search", await searchContext.ToListAsync());
        }

        // GET: Apps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || id == 49) //default app
            {
                return RedirectToAction("NotFound", "Home");
            }

            var app = await _context.Apps.Include(a => a.Category).Include(l => l.Logo).
                Include(v => v.Videos).Include(i => i.Images).Include(r => r.Review).
                ThenInclude(u => u.UserName).FirstOrDefaultAsync(m => m.Id == id);
            if (app == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            string userName = User.Identity.Name;
            var usr = _context.User.Include(u => u.PaymentMethods).Include(u => u.AppListUser);
            foreach (var item in usr)
            {
                if (item.Name.Equals(userName))
                {
                    ViewData["UserInfo"] = item;
                    ViewData["UserPMcount"] = item.PaymentMethods.Count();
                }
            }

            return View(app);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        // GET: Apps/Create
        public IActionResult Create()
        {
            String userName = User.Identity.Name;

            ViewData["CategoryId"] = new SelectList(_context.Category.Where(c => c.Id != 9), "Id", "Name");
            ViewData["Images"] = new SelectList(_context.AppsImage.Include(a => a.App).Where(x => x.App.DeveloperName.Equals(userName) || x.AppId == 49), "Id", "Name");
            ViewData["Videos"] = new SelectList(_context.AppVideo.Include(a => a.App).Where(x => x.App.DeveloperName.Equals(userName) || x.AppId == 49), "Id", "Name");

            return View();
        }

        // POST: Apps/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Description,publishDate,Logo,CategoryId,Size," +
                                                "AverageRaiting,countReview,DeveloperName,Images,Videos")] App app, int[] Images, int[] Videos)
        {
            if (ModelState.IsValid)
            {
                Logo log = new Logo(); //create app's logo 
                log.Image = app.Logo.Image;
                log.Apps = app;
                log.AppsId = app.Id;
                _context.Add(log);

                app.publishDate = DateTime.Now;
                app.Logo = log;

                app.Images = new List<AppImage>();
                app.Images.AddRange(_context.AppsImage.Where(x => Images.Contains(x.Id)));
                foreach (var item in app.Images) //connect app images to the app
                {
                    item.AppId = app.Id;
                    item.App = app;
                }

                app.Videos = new List<AppVideo>();
                app.Videos.AddRange(_context.AppVideo.Where(x => Videos.Contains(x.Id)));
                foreach (var item in app.Videos)  //connect app video to the app
                {
                    item.AppId = app.Id;
                    item.App = app;
                }

                _context.Add(app);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            String userName = User.Identity.Name;

            ViewData["CategoryId"] = new SelectList(_context.Category.Where(c => c.Id != 9), "Id", "Name", app.CategoryId);
            ViewData["Images"] = new SelectList(_context.AppsImage.Include(a => a.App).Where(x => x.App.DeveloperName.Equals(userName) || x.AppId == 49), "Id", "Name");
            ViewData["Videos"] = new SelectList(_context.AppVideo.Include(a => a.App).Where(x => x.App.DeveloperName.Equals(userName) || x.AppId == 49), "Id", "Name");

            return View(app);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        // GET: Apps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 49) //default app
            {
                return RedirectToAction("NotFound", "Home");
            }
            var app = await _context.Apps.FindAsync(id);
            if (app == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            string userName = User.Identity.Name;
            string appDevName = _context.Apps.Find(id).DeveloperName;
            Boolean isAdmin = User.IsInRole("Admin");
            if ((!userName.Equals(appDevName)) && !isAdmin)
            {
                return RedirectToAction("AccessDenied", "Users");
            }

            ViewData["CategoryId"] = new SelectList(_context.Category.Where(c => c.Id != 9), "Id", "Name", app.CategoryId);

            Logo logo = null;
            var apps = _context.Apps.Include(x => x.Logo).Include(y => y.Images).Include(z => z.Videos);
            foreach (var item in apps)
            {
                if (item.Id == id)
                {
                    logo = item.Logo;
                    break;
                }
            }
            ViewData["Logo"] = logo;

            var AppReview = _context.Apps.Include(a => a.Review);
            foreach (var item in AppReview)
            {
                if (item.Id == id)
                {
                    ViewData["countReview"] = item.countReview;
                    ViewData["AverageRaiting"] = item.AverageRaiting;
                    break;
                }
            }

            var CurrentApp = await _context.Apps.Include(a => a.Images).Include(b => b.Videos).FirstOrDefaultAsync(m => m.Id == id);
            ViewData["Images"] = new SelectList(CurrentApp.Images, "Id", "Name");
            ViewData["Videos"] = new SelectList(CurrentApp.Videos, "Id", "Name");

            return View(app);
        }

        // POST: Apps/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Description,publishDate,Logo,CategoryId,Size,AverageRaiting," +
                                            "countReview, DeveloperName,Images,Videos")] App app, int[] Images, int[] Videos)
        {
            if (id != app.Id || id == 49) //default app
            {
                return RedirectToAction("NotFound", "Home");
            }

            foreach (var item in _context.Logo) //get viewdata[Logo] (in case validation is false)
            {
                if (item.AppsId == app.Id)
                {
                    ViewData["Logo"] = item;
                    break;
                }
            }
            await _context.SaveChangesAsync();

            if (ModelState.ErrorCount == 2)
            {
                if (ModelState.ContainsKey("Images") && ModelState.ContainsKey("Videos"))
                    ModelState.Clear();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    foreach (var item in _context.Logo)
                    {
                        if (item.AppsId == app.Id)
                        {
                            item.Image = app.Logo.Image;
                            _context.Update(item);
                            app.Logo = item;
                            break;
                        }
                    }

                    app.publishDate = DateTime.Now;
                    _context.Update(app);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppExists(app.Id))
                    {
                        return RedirectToAction("NotFound", "Home");
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "Name", app.CategoryId);
            return View(app);
        }

        // GET: Apps/Delete/5
        [HttpGet]

ColmanAppStore/Controllers/LogoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ColmanAppStore.Data;
using ColmanAppStore.Models;
using Microsoft.AspNetCore.Authorization;

namespace ColmanAppStore.Controllers
{
    public class LogoesController : Controller
    {
        private readonly ColmanAppStoreContext _context;

        public LogoesController(ColmanAppStoreContext context)
        {
            _context = context;
        }

        // GET: Logoes
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Index()
        {
            String userName = User.Identity.Name;
            foreach (var item in _context.User)
            {
                if (item.Name.Equals(userName))
                {
                    if (User.IsInRole("Admin")) //admin user
                    {
                        return View(await _context.Logo.Include(a => a.Apps).ToListAsync());
                    }
                    else //programer user
                    {
                        var colmanAppStoreContext = _context.Logo.Include(a => a.Apps).Where(x => x.Apps.DeveloperName.Equals(item.Name));
                        return View(await colmanAppStoreContext.ToListAsync());
                    }
                }
            }
            // in case couldn't find the user (can't happen when logged in)
            return View(await _context.Logo.ToListAsync());
        }

        // GET: Logoes/Details/5
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var logo = await _context.Logo.Include(l => l.Apps).FirstOrDefaultAsync(m => m.Id == id);
            if (logo == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(logo);
        }

        // GET: Logoes/Create
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public IActionResult Create()
        {
            return RedirectToAction("NotFound", "Home");
        }

        // POST: Logoes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Create([Bind("Id,Image,AppsId")] Logo logo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(logo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppsId"] = new SelectList(_context.Apps.Where(a => a.Id != 49), "Id", "Name", logo.AppsId);
            return View(logo);
        }

        // GET: Logoes/Edit/5
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var logo = await _context.Logo.Include(l => l.Apps).FirstOrDefaultAsync(m => m.Id == id);
            if (logo == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            string userName = User.Identity.Name;
            string appDevName = _context.Logo.Find(id).Apps.DeveloperName;
            Boolean isAdmin = User.IsInRole("Admin");
            if (!(userName.Equals(appDevName)) && !isAdmin)
            {
                return RedirectToAction("AccessDenied", "Users");
            }

            var apps = _context.Apps.Include(l => l.Logo).Where(a => a.Id != 49);
            foreach (var item in apps)
            {
                if (item.Logo.Id == id)
                {
                    ViewData["AppsId"] = item.Id;
                    ViewData["App"] = item;
                    break;
                }
            }
            return View(logo);
        }

        // POST: Logoes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Image,AppsId")] Logo logo)
        {
            if (id != logo.Id)
            {
                return RedirectToAction("NotFound", "Home");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(logo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LogoExists(logo.Id))
                    {
                        return RedirectToAction("NotFound", "Home");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppsId"] = new SelectList(_context.Apps.Where(a => a.Id != 49), "Id", "Name", logo.AppsId);
            return View(logo);
        }

        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> SearchLogo(string query)//search by app name
        {
            string userName = User.Identity.Name;
            var searchContext = _context.Logo.Include(l => l.Apps).
                 Where(a => a.Apps.Name.Contains(query) || (query == null));
            if (!User.IsInRole("Admin")) // if developer - he will see only his apps (admin sees everything)
            {
                searchContext = _context.Logo.Include(l => l.Apps).
                  Where(a => a.Apps.Name.Contains(query) || (query == null)).Where(u => u.Apps.DeveloperName.Equals(userName));
            }
            return View("SearchLogo", await searchContext.ToListAsync());
        }

        // GET: Logoes/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var logo = await _context.Logo.Include(l => l.Apps).FirstOrDefaultAsync(m => m.Id == id);
            if (logo == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            string userName = User.Identity.Name;
            string appDevName = _context.Logo.Find(id).Apps.DeveloperName;
            Boolean isAdmin = User.IsInRole("Admin");
            if (!(userName.Equals(appDevName)) && !isAdmin)
            {
                return RedirectToAction("AccessDenied", "Users");
            }

            return View(logo);
        }

        // POST: Logoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Programer")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var logo = await _context.Logo.FindAsync(id);
            _context.Logo.Remove(logo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LogoExists(int id)
        {
            return _context.Logo.Any(e => e.Id == id);
        }
    }
}

ColmanAppStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ColmanAppStore</title>

    <link rel="stylesheet" href="/css/Layout.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/js/site.js" />

</head>

<body>

    <header id="header">
        <div class="header container-fluid">
            <div class="d-flex justify-content-between">
                <div class="row header__row align-items-center">
                    <div class="col-sm-2 " style="text-align:center">
                        <a class="logoStyle" asp-action="HomePage" asp-controller="Apps">
                            <img class="logo" src="~/LogoImage/ColmanAppStoreLogo.jpg" alt="logo" style="max-width: 40%;margin:auto;" />


                        </a>
                    </div>
                    <div class="col-sm-6">
                        <div class="input-group rounded justify-content-center">
                            <form asp-action="Search" asp-controller="Apps" class="d-flex">
                                <input id="font" name="query" type="search" class="form-control" placeholder="Search " aria-label="Search" aria-describedby="search-addon" autocomplete="off" />
                                <div id="slider-range"></div>
                                <button type="submit" class="btn btn-primary btn_search">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" class="bi bi-search" viewBox="0 0 18 18">
                                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                                    </svg>

                                </button>
                            </form>
                        </div>
                    </div>

                    <div class="col-sm-2  header d-flex justify-content-center" id="darkBtnStyle">
                        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">

                        <div class="theme-switch-wrapper">
                            <label class="theme-switch" for="checkbox">
                                <input type="checkbox" id="checkbox" />
                                <div class="slider round"></div>
                            </label>
                            <label id="labelMode">Select Mode</label>
                        </div>
                    </div>

                    <div class="col-sm-2 header d-flex justify-content-center">

                        @if (Context.User.Identity != null && Context.User.Claims != null && Context.User.Claims.Count() > 0)
                        {
                            <div class="dropdown">
                                <button id="font" class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Hello @User.Identity.Name!

                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a id="font" asp-action="Account" asp-controller="Users" asp-route-id="@User.Identity.Name">My Account</a></li>
                                    @if (User.IsInRole("Admin") || User.IsInRole("Programer"))
                                    {
                                        <a id="font" asp-action="Create" asp-controller="Apps">Create an App</a>
                                    }
                                    <li><a id="font" asp-action="Logout" asp-controller="Users">Logout</a></li>

                                </ul>
                            </div>
                        }
                        else
                        {
                            <a id="font" asp-action="Login" asp-controller="Users" class="btn btn-primary btn_login">Login</a>
                            <a id="font" asp-action="Register" asp-controller="Users" class="btn btn-primary btn_signup"> SignUp</a>
                        }

                    </div>
                </div>
            </div>
        </div>
    </header>

    <main>
        <div class="d-flex ">
            <div class="row">
                <aside class="col-sm-2 col-navbar" id="navBarStyle">

                    <div class="d-flex align-items-stretch">
                        <link rel="preconnect" href="https://fonts.gstatic.com">
                        <link href="https://fonts.googleapis.com/css2?family=Days+One&family=Indie+Flower&family=Nunito:wght@700;800&display=swap" rel="stylesheet">

                        <nav class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">

                            @*navbar for unlogged user*@
                            <a id="col-btn" class="btn btn-primary" asp-action="HomePage" asp-controller="Apps">Home</a>
                            <a id="col-btn" class="btn btn-primary" asp-action="index" asp-controller="Categories">Categories</a>
                            <a id="col-btn" class="btn btn-primary" asp-action="Index" asp-controller="Apps">All apps</a>

                            @*if user logged in*@
                            @if (Context.User.Identity != null && Context.User.Claims != null && Context.User.Claims.Count() > 0)
                            {
                                <a id="col-btn" class="btn btn-primary" asp-action="Index" asp-controller="Payments">Payments</a>

                                if (User.IsInRole("Programer") || User.IsInRole("Admin"))
                                {
                                    <a id="col-btn" class="btn btn-primary" asp-action="Index" asp-controller="Logoes">Logoes</a>
                                    <a id="col-btn" class="btn btn-primary" asp-action="Index" asp-controller="AppImages">App images</a>
                                    <a id="col-btn" class="btn btn-primary" asp-action="Index" asp-controller="AppVideos">App videos</a>
                                }

                                if (User.IsInRole("Admin"))
                                {
                                    <a id="col-btn" class="btn btn-primary" asp-action="Index" asp-controller="Reviews">All reviews</a>
                                    <a id="col-btn" class="btn btn-primary" asp-action="Index" asp-controller="Users">All users</a>
                                    <a id="col-btn" class="btn btn-primary" asp-action="Graph" asp-controller="Apps">Statistics</a>
                                }
                            }
                        </nav>

                    </div>
                    <a class="weatherwidget-io" href="https://forecast7.com/en/32d0934d78/tel-aviv-yafo/" data-label_1="TEL AVIV" data-label_2="WEATHER" data-font="Verdana" data-icons="Climacons Animated" data-mode="Current" data-days="3" data-theme="original">Tel Aviv weather</a>
                    <script>
                        !function (d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0];
                            if (!d.getElementById(id)) {
                                js = d.createElement(s);
                                js.id = id; js.src = 'https://weatherwidget.io/js/widget.min.js';
                                fjs.parentNode.insertBefore(js, fjs);
                            }
                        }(document, 'script', 'weatherwidget-io-js');
                    </script>
                </aside>

                <div class="col-sm-10 col-lines" id="fullBG">
                    <main role="main" class="pb-3" id="mainWindow">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </main>

    <footer class="border-top footer text-muted" id="footerStyle">
        <div class="container-fluid">
            &copy; 2021 - ColmanAppStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> -
            <a asp-area="" asp-controller="Home" asp-action="About">About Us</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

</body>
</html>