ColmanAppStore/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ColmanAppStore.Models
{
    public class Payment
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "You must enter name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "You must enter address")]
        public String Address { get; set; }

        [Required(ErrorMessage = "You must enter city")]
        public String City { get; set; }

        [Required]
        [Display(Name = "Payment methods")]
        public int PaymentMethodId { get; set; }

        public PaymentMethod PaymentMethod { get; set; } //ONE payment method to MANY payments

        [Display(Name = "App name")]
        public int AppId { get; set; }

        public App App { get; set; }
    }
}

ColmanAppStore/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ColmanAppStore.Data;
using ColmanAppStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Routing;

namespace ColmanAppStore.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly ColmanAppStoreContext _context;

        public PaymentsController(ColmanAppStoreContext context)
        {
            _context = context;
        }

        // GET: Payments
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Index()
        {
            String userName = User.Identity.Name;
            var usr = _context.User.Include(a => a.AppListUser).Include(p => p.PaymentMethods);
            foreach (var item in usr)
            {
                if (item.Name.Equals(userName))
                {
                    var payments = _context.Payment.Include(p => p.App).Include(p => p.PaymentMethod).
                        Where(a => item.AppListUser.Contains(a.App)).Where(p => item.PaymentMethods.Contains(p.PaymentMethod));
                    return View(await payments.ToListAsync());
                }
            }
            //in case user won't be found (never going to happen when logged in)
            return View(await _context.Payment.Include(p => p.App).Include(p => p.PaymentMethod).ToListAsync());
        }

        // GET: Payments/Details/5
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var payment = await _context.Payment.Include(p => p.App).Include(p => p.PaymentMethod).FirstOrDefaultAsync(m => m.Id == id);
            if (payment == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            int count = 0;
            string userName = User.Identity.Name;
            int methodId = payment.PaymentMethodId;
            var payMethod = _context.PaymentMethod.Include(u => u.Users).FirstOrDefault(m => m.Id == methodId);
            var usr = payMethod.Users;
            User myUsr = _context.User.Where(i => i.Name.Equals(userName)).First();
            int myId = myUsr.Id;
            foreach (var item in usr)
            {
                if (item.Id.Equals(myId))
                {
                    count++;
                    break;
                }
            }
            if (count == 0)
            {
                return RedirectToAction("AccessDenied", "Users");
            }
            return View(payment);
        }

        // GET: Payments/Create
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            ViewData["AppId"] = id;
            var application = new App();
            int count = 0;
            foreach (var item in _context.Apps)
            {
                if (item.Id == id)
                {
                    count++;
                    ViewData["App"] = item;
                    application = item;
                    break;
                }
            }
            if (count == 0) //there is no such app
            {
                return RedirectToAction("NotFound", "Home");
            }

            String userName = User.Identity.Name;
            User connectedUser = null;
            foreach (var item in _context.User)
            {
                if (item.Name.Equals(userName))
                {
                    connectedUser = item;
                    break;
                }
            }

            var usr = _context.User.Include(u => u.PaymentMethods).Include(u => u.AppListUser);

            List<PaymentMethod> paymentM = new List<PaymentMethod>();
            foreach (var item in usr)
            {

                if (item.Equals(connectedUser))
                {
                    foreach (var us in item.PaymentMethods)
                    {
                        if (item.AppListUser.Contains(application)) // checks if the user already purchased the app
                            return RedirectToAction("details", "Apps", new { id = id });
                        paymentM.Add(us);
                    }
                    break;
                }
            }

            ViewData["PaymentMethodId"] = new SelectList(paymentM, "Id", "CardNumber");

            return View();
        }

        // POST: Payments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,City,PaymentMethodId,AppId")] Payment payment, string userName)
        {
            if (ModelState.IsValid)
            {
                App purchasedApp = null;
                foreach (var item in _context.Apps)
                {
                    if (item.Id == payment.AppId)
                    {
                        purchasedApp = item;
                        break;
                    }
                }

                var usr = _context.User.Include(u => u.PaymentMethods).Include(u => u.AppListUser);
                foreach (var item in usr)
                {
                    if (item.Name.Equals(userName))
                    {
                        if (item.AppListUser == null)
                            item.AppListUser = new List<App>();
                        item.AppListUser.Add(purchasedApp);
                        _context.Update(item);
                        break;
                    }
                }

                payment.Id = 0; //be updated after added to DB
                _context.Add(payment);
                await _context.SaveChangesAsync();
                return RedirectToAction("HomePage", "Apps");
            }
            ViewData["AppId"] = new SelectList(_context.Apps, "Id", "Name", payment.AppId);

            return View(payment);
        }


        // GET: Payments/Edit/5
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var payment = await _context.Payment.FindAsync(id);
            if (payment == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            ViewData["AppId"] = new SelectList(_context.Apps, "Id", "Name", payment.AppId);
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethod, "Id", "ExpiredDate", payment.PaymentMethodId);
            return View(payment);
        }

        // POST: Payments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,City,PaymentMethodId,AppId")] Payment payment)
        {
            if (id != payment.Id)
            {
                return RedirectToAction("NotFound", "Home");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.Id))
                    {
                        return RedirectToAction("NotFound", "Home");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["AppId"] = new SelectList(_context.Apps, "Id", "Name", payment.AppId);
            ViewData["PaymentMethodId"] = new SelectList(_context.PaymentMethod, "Id", "ExpiredDate", payment.PaymentMethodId);
            return View(payment);
        }

        // GET: Payments/Delete/5
        [HttpGet]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var payment = await _context.Payment.Include(p => p.App).Include(p => p.PaymentMethod).FirstOrDefaultAsync(m => m.Id == id);
            if (payment == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Client,Admin,Programer")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payment = await _context.Payment.FindAsync(id);

            App purchasedApp = null;
            foreach (var item in _context.Apps)
            {
                if (item.Id == payment.AppId)
                {
                    purchasedApp = item;
                    break;
                }
            }

            String userName = User.Identity.Name;
            var usr = _context.User.Include(u => u.PaymentMethods).Include(u => u.AppListUser);
            foreach (var item in usr)
            {
                if (item.Name.Equals(userName))
                {
                    item.AppListUser.Remove(purchasedApp);
                    _context.Update(item);
                    break;
                }
            }

ColmanAppStore/Views/Payments/AppBuyers.cshtml
@model Join

@{
    ViewData["Title"] = " Apppayment";
    <link rel="stylesheet" href="~/css/paymentStyle.css" />
}

<h1 id="paymentHeader">Buyers list</h1>

<div>
    <div class="ManagerOverviewPageWrapper">

        @if (Model.Users.Count > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Name
                        </th>
                        <th>
                            Address
                        </th>
                        <th>
                            City
                        </th>
                        <th>
                            Payment Method number
                        </th>
                        <th>
                            App name
                        </th>
                        <th>
                            App details
                        </th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (Payment user in Model.Users)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => user.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => user.Address)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => user.City)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => user.PaymentMethod.CardNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => user.App.Name)
                            </td>
                            <td>
                                <a class="btn btn-outline-info" asp-controller="Apps" asp-action="Details" asp-route-id="@user.AppId">Back to @user.App.Name <i class="fas fa-info"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <br />
            <h3 id="subtitle">No one bought this app!</h3>
        }
    </div>
</div>

ColmanAppStore/Views/Payments/Create.cshtml
@model ColmanAppStore.Models.Payment

@{
    ViewData["Title"] = "Create payment";
    <link rel="stylesheet" href="~/css/paymentStyle.css" />
}

<h1 id="paymentHeader">Create payment for @ViewBag.App.Name</h1>

<div class="card_payment col-12" id="cardStyle">
    <div class="card-body">
        <div class="row">
            <div class="col-75">
                <div class="container" id="containerStyle">
                    <form asp-action="Create">
                        <input type="hidden" name="AppId" value="@ViewBag.AppId" />
                        <input type="hidden" name="UserName" value="@User.Identity.Name" />

                        <div class="row">
                            <div class="col-md-4">
                                <h3>Billing Address</h3>
                                <div class="form-group">
                                    <label for="fname"><i class="fa fa-user"></i> Full Name</label>
                                    <input asp-for="Name" class="form-control" autocomplete="off" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
                                    <input asp-for="Address" class="form-control" autocomplete="off" />
                                    <span asp-validation-for="Address" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label for="city"><i class="fa fa-institution"></i> City</label>
                                    <input asp-for="City" class="form-control" autocomplete="off" />
                                    <span asp-validation-for="City" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <h3>Payment</h3>

                                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> @*credit card icons link*@

                                <div class="form-group">
                                    <label asp-for="PaymentMethodId" class="control-label"></label>
                                    <select asp-for="PaymentMethodId" class="form-control" asp-items="ViewBag.PaymentMethodId"></select>
                                </div>

                                <div class="icon-container" id="cardTitle">
                                    <label for="fname" id="AcceptedTitle">Accepted Cards</label>
                                    <i class="fa fa-cc-visa" id="visaStyle"></i>
                                    <i class="fa fa-cc-amex" id="amexStyle"></i>
                                    <i class="fa fa-cc-mastercard" id="mastercardStyle"></i>
                                    <i class="fa fa-cc-discover" id="discoverStyle"></i>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <h4>
                                    Cart
                                    <span class="price" id="cartTitle">
                                        &ensp; @*move 2 spaces for style*@
                                        <i class="fa fa-shopping-cart"></i>
                                        <b>1</b>
                                    </span>
                                </h4>
                                <br />

                                <p><a id="cartApp"></a> @ViewBag.App.Name<span class="price" id="cartAppPrice"> @ViewBag.App.Price ₪</span></p>
                                <hr>
                                <p id="totalCart">Total <span class="price" id="totalPriceCart"><b> @ViewBag.App.Price ₪</b></span></p>

                            </div>
                        </div>

                        <input type="submit" value="Continue to checkout" class="btn" id="submitButton">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ColmanAppStore/Views/Payments/Delete.cshtml
@model ColmanAppStore.Models.Payment

@{
    ViewData["Title"] = "Delete payment";
    <link rel="stylesheet" href="~/css/paymentStyle.css" />
}

<h1 id="paymentHeader">Delete @Model.App.Name</h1>

<h4 id="subTitleHeader">Are you sure you want to delete this payment?</h4>
<div>
    <hr />
    <div class="card_payment col-12" id="cardDetails">
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Address)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Address)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.City)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.City)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.PaymentMethod.CardNumber)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.PaymentMethod.CardNumber)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.PaymentMethod.ExpiredDate)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.PaymentMethod.ExpiredDate)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.App.Price)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.App.Price)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.App)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.App.Name)
                </dd>
            </dl>
            <br />
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a asp-action="Index">Back to all payments</a>
            </form>
        </div>
    </div>
</div>

ColmanAppStore/Views/Payments/Details.cshtml
@model ColmanAppStore.Models.Payment

@{
    ViewData["Title"] = Model.App.Name + " payment";
    <link rel="stylesheet" href="~/css/paymentStyle.css" />
}

<h1 id="paymentHeader">@Model.App.Name payment</h1>

<div>
    <hr />
    <div class="card_payment col-12" id="cardDetails">
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.Address)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.Address)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.City)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.City)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.PaymentMethod.CardNumber)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.PaymentMethod.CardNumber)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.PaymentMethod.ExpiredDate)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.PaymentMethod.ExpiredDate)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.App.Price)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.App.Price)
                </dd>
                <dt class="col-sm-6">
                    @Html.DisplayNameFor(model => model.App)
                </dt>
                <dd class="col-sm-6">
                    @Html.DisplayFor(model => model.App.Name)
                </dd>
            </dl>
            <br />
            <a href="/Apps/Details/@Model.AppId" class="btn btn-info">Go to @Model.App.Name</a>
            <br />
            <div>
                <a asp-action="Index">Back to all payments</a>
            </div>
        </div>
    </div>
</div>

ColmanAppStore/Views/Payments/Edit.cshtml
@model ColmanAppStore.Models.Payment

@{
    ViewData["Title"] = "Edit payment";
    <link rel="stylesheet" href="~/css/paymentStyle.css" />
}

<br />
<h1 id="PageHeader">Sorry, you can't edit completed payment</h1>

<div id="backBtn">
    <br />
    <a class="btn btn-info" asp-action="Index">Back to all payment</a>
</div>

ColmanAppStore/Views/Payments/Index.cshtml
@model IEnumerable<ColmanAppStore.Models.Payment>

@{
    ViewData["Title"] = "All payments";
    <link rel="stylesheet" href="~/css/paymentStyle.css" />
}

<div class="row">
    <div class="col-lg-9 col-md-10">
        <h1 id="PaymentHeaderSearch">All Payments</h1>
    </div>

    <div class="col-lg-3 col-md-2">
        <form id="searchPayment" asp-action="searchPayment" asp-controller="Payments" class="d-flex">
            <input id="font" name="query" type="search" class="form-control" placeholder="Search by App Name" aria-label="Search" aria-describedby="search-addon" autocomplete="off" />
            <div id="slider-range"></div>
        </form>
    </div>
</div>

@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                @*<th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PaymentMethod.CardNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PaymentMethod.ExpiredDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.App.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.App)
                </th>
                <th>
                    Details
                </th>
                <th>
                    Delete
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PaymentMethod.CardNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PaymentMethod.ExpiredDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.App.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.App.Name)
                    </td>
                    <td>
                        <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Details</a>

                    </td>
                    <td>
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <br />
    <h2 class="text-center" id="PageHeader">Sorry, you don't have any payments</h2>
    <br />
}

ColmanAppStore/Views/Payments/SearchPayment.cshtml
@model IEnumerable<ColmanAppStore.Models.Payment>

@{
    ViewData["Title"] = "All payments";
    <link rel="stylesheet" href="~/css/paymentStyle.css" />
}

<div class="row">
    <div class="col-lg-9 col-md-10">
        <h1 id="PaymentHeaderSearch">Search results</h1>
    </div>

    <div class="col-lg-3 col-md-2">
        <form id="searchPayment" asp-action="SearchPayment" asp-controller="Payments" class="d-flex">
            <input id="font" name="query" type="search" class="form-control" placeholder="Search by App Name" aria-label="Search" aria-describedby="search-addon" autocomplete="off" />
            <div id="slider-range"></div>
        </form>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <!-- <th>
                 @Html.DisplayNameFor(model => model.Name)
             </th> -->
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentMethod.CardNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentMethod.ExpiredDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.App.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.App)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <!--  <td>
                      @Html.DisplayFor(modelItem => item.Name)
                  </td> -->
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentMethod.CardNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentMethod.ExpiredDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.App.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.App.Name)
                </td>
                <td>
                    <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Details</a> 
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>